on:
  pull_request:
  push:
    branches:
      - main
      - yay

name: run tests
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.17.x
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run linters
      uses: golangci/golangci-lint-action@v6
    - name: static code analyse
      run: go vet ./...

  test:
    needs: lint
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run tests
      run: go test -v -covermode=count ./...

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v5
      with:
        go-version: 1.17.x
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Calc coverage
      run: |
        COVERAGE=$(go test -v -covermode=count -coverprofile=coverage.out ./... | grep "^coverage:" | cut -d' ' -f2)
        echo "COVERAGE=$(echo ${COVERAGE})" >> $GITHUB_ENV
        if [ "x${{ github.head_ref }}" == "x" ]; then
          BRANCH_NAME=$(echo ${{github.ref}} | cut -d'/' -f3)
        else
          BRANCH_NAME=${{github.head_ref}}
        fi
        echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV
        COLOR=orange
        COVERAGE_NUMBER=$(echo ${COVERAGE} | cut -d'%' -f1)
        if [ 1 -eq "$(echo "${COVERAGE_NUMBER} < 60"| bc)" ]; then
          color=red
        elif [ 1 -eq "$(echo "${COVERAGE_NUMBER} > 85"| bc)" ]; then
          color=green
        fi
        echo "COLOR=$(echo ${color})" >> $GITHUB_ENV
    - name: Create the Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: 97d98d096e648370e2848116f7f8289a
        filename: ulid_uuid__${{ env.BRANCH }}.json
        label: coverage
        message: ${{ env.COVERAGE }}
        color: ${{ env.COLOR }}
#    - name: Convert coverage.out to coverage.lcov
#      uses: jandelgado/gcov2lcov-action@v1.0.6
#    - name: Coveralls
#      uses: coverallsapp/github-action@v1.1.2
#      with:
#          github-token: ${{ secrets.github_token }}
#          path-to-lcov: coverage.lcov
